import streamlit as st
import feedparser
import urllib.request
import re
import pandas as pd
from datetime import datetime
from fpdf import FPDF

# Page configuration
st.set_page_config(
    page_title="Agri Pulse AI - Global Agricultural Dashboard",
    page_icon="🌾",
    layout="wide"
)

# Custom Styling (CSS)
st.markdown("""
<style>
    .main-title {
        font-size: 2.3rem;
        font-weight: 700;
        color: #2E7D32;
        margin-bottom: 0px;
    }
    .sub-title {
        color: #555555;
        font-size: 1rem;
        margin-bottom: 25px;
    }
    .news-card {
        background-color: #f9fbf9;
        padding: 18px;
        border-radius: 10px;
        border-left: 5px solid #2E7D32;
        margin-bottom: 15px;
        box-shadow: 0 1px 3px rgba(0,0,0,0.1);
    }
</style>
""", unsafe_allow_html=True)

# App Header
st.markdown('<div class="main-title">🌾 Agri Pulse AI Dashboard</div>', unsafe_allow_html=True)
st.markdown('<div class="sub-title">Real-time global agricultural market intelligence and automated AI summaries.</div>', unsafe_allow_html=True)

# Expanded Feeds List
rss_feeds = {
    "All Feeds Combined": "COMBINED",
    "ScienceDaily - Ag & Food Research": "https://www.sciencedaily.com/rss/plants_animals/agriculture_and_food.xml",
    "Farms.com - Global Industry News": "https://m.farms.com/farmspages/generate_rss_portal/tabid/2854/default.aspx",
    "BBC - Climate & Environment": "https://feeds.bbci.co.uk/news/science_and_environment/rss.xml"
}

# Helper Functions
def fetch_feed(url):
    try:
        req = urllib.request.Request(
            url, 
            headers={'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/120.0.0.0 Safari/537.36'}
        )
        xml_data = urllib.request.urlopen(req, timeout=10).read()
        return feedparser.parse(xml_data)
    except Exception as e:
        st.error(f"Error connecting to server: {e}")
        return None

def clean_html(raw_html):
    return re.sub(re.compile('<.*?>'), '', raw_html)

def clean_filename(title):
    clean_str = re.sub(r'[^\w\s-]', '', title)
    clean_str = re.sub(r'[\s-]+', '_', clean_str).strip('_')
    return clean_str[:40]

def call_ai_summary(text, api_key):
    try:
        from openai import OpenAI
        client = OpenAI(base_url="https://api.groq.com/openai/v1", api_key=api_key)
        response = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[
                {"role": "system", "content": "You are an expert agronomy consultant. Provide a 2-bullet point summary highlighting key agricultural implications."},
                {"role": "user", "content": text}
            ],
            max_tokens=150
        )
        return response.choices[0].message.content
    except Exception as err:
        return f"AI Service Error: {err}"

# Pure Python PDF Generator Class
class AgriPDFReport(FPDF):
    def header(self):
        self.set_fill_color(27, 94, 32)
        self.rect(0, 0, 210, 25, 'F')
        self.set_font('Arial', 'B', 14)
        self.set_text_color(255, 255, 255)
        self.cell(0, 8, 'Agri Pulse AI -- Intelligence Report', 0, 1, 'L')
        self.set_font('Arial', '', 9)
        self.cell(0, 4, 'Agricultural Market & Research Briefing', 0, 1, 'L')
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by Agri Pulse AI Dashboard', 0, 0, 'C')

def generate_pdf_report(source_name, entries):
    pdf = AgriPDFReport()
    pdf.add_page()
    
    pdf.set_font('Arial', 'B', 10)
    pdf.set_text_color(46, 125, 50)
    pdf.cell(35, 6, "Source Feed:", 0, 0)
    pdf.set_font('Arial', '', 10)
    pdf.set_text_color(50, 50, 50)
    pdf.cell(60, 6, source_name, 0, 0)
    
    pdf.set_font('Arial', 'B', 10)
    pdf.set_text_color(46, 125, 50)
    pdf.cell(35, 6, "Date Generated:", 0, 0)
    pdf.set_font('Arial', '', 10)
    pdf.set_text_color(50, 50, 50)
    pdf.cell(0, 6, datetime.now().strftime("%B %d, %Y"), 0, 1)
    
    pdf.ln(5)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(5)
    
    pdf.set_font('Arial', 'B', 12)
    pdf.set_text_color(27, 94, 32)
    pdf.cell(0, 8, f"Aggregated News Summaries (Total: {len(entries)})", 0, 1)
    pdf.ln(2)

    # NO LIMIT: Generates PDF rows for every single entry supplied
    for idx, item in enumerate(entries, 1):
        pdf.set_font('Arial', 'B', 10)
        pdf.set_text_color(27, 94, 32)
        safe_title = item.title.encode('latin-1', 'replace').decode('latin-1')
        pdf.multi_cell(0, 5, f"{idx}. {safe_title}")
        
        pub_date = getattr(item, 'published', getattr(item, 'updated', 'Recent'))
        pdf.set_font('Arial', 'I', 8)
        pdf.set_text_color(128, 128, 128)
        pdf.cell(0, 4, f"Published: {pub_date}", 0, 1)
        
        summary_text = clean_html(getattr(item, 'summary', 'No summary available.'))[:350]
        safe_summary = summary_text.encode('latin-1', 'replace').decode('latin-1')
        
        pdf.set_font('Arial', '', 9)
        pdf.set_text_color(60, 60, 60)
        pdf.multi_cell(0, 4.5, f"{safe_summary}...")
        pdf.ln(4)

    return bytes(pdf.output())

# Sidebar Controls
with st.sidebar:
    st.header("⚙️ Dashboard Controls")
    selected_source = st.selectbox("📰 Select News Source", list(rss_feeds.keys()))
    
    st.divider()
    st.header("🤖 AI Integration Settings")
    ai_key = st.text_input("Enter Groq / OpenAI API Key", type="password", help="Get a free key from console.groq.com")
    ai_enabled = st.checkbox("Enable AI Article Summaries", value=False)

# Data Fetching Logic (Supports Single Source or Combined)
all_entries = []

if rss_feeds[selected_source] == "COMBINED":
    for name, url in rss_feeds.items():
        if url != "COMBINED":
            parsed = fetch_feed(url)
            if parsed and parsed.entries:
                all_entries.extend(parsed.entries)
else:
    parsed = fetch_feed(rss_feeds[selected_source])
    if parsed and parsed.entries:
        all_entries = parsed.entries

if all_entries:
    # Top Metrics
    col1, col2, col3 = st.columns(3)
    col1.metric("Active Source", selected_source.split(" - ")[0])
    col2.metric("Total Articles Loaded", len(all_entries))
    col3.metric("System Status", "Live Connection 🟢")

    st.divider()

    # Search Bar
    search_term = st.text_input("🔍 Search Articles by Keyword / Crop Name", "").lower()

    filtered_entries = [
        entry for entry in all_entries 
        if search_term in entry.title.lower() or search_term in getattr(entry, 'summary', '').lower()
    ]

    st.subheader(f"Showing Articles ({len(filtered_entries)} Total Loaded)")

    # Render Cards (Unlimited Loop)
    for idx, entry in enumerate(filtered_entries):
        clean_summary = clean_html(getattr(entry, 'summary', 'No summary available.'))
        pub_date = getattr(entry, 'published', getattr(entry, 'updated', 'Recent'))
        article_slug = clean_filename(entry.title)
        
        with st.container():
            st.markdown(f"### [{idx+1}. {entry.title}]({entry.link})")
            st.caption(f"📅 Published: {pub_date}")
            st.write(clean_summary[:300] + ("..." if len(clean_summary) > 300 else ""))
            
            if ai_enabled:
                if ai_key:
                    with st.expander("✨ View AI Insights & Agronomy Summary"):
                        with st.spinner("Analyzing article..."):
                            summary_result = call_ai_summary(clean_summary, ai_key)
                            st.write(summary_result)
                else:
                    st.warning("Please enter your API key in the sidebar menu to unlock AI Summaries.")
            
            # Individual Article Download Buttons
            d_col1, d_col2 = st.columns(2)
            
            single_csv = pd.DataFrame([{
                "Title": entry.title,
                "Published Date": pub_date,
                "Link": entry.link,
                "Summary": clean_summary
            }]).to_csv(index=False).encode('utf-8')
            
            d_col1.download_button(
                label="📊 Export Article CSV",
                data=single_csv,
                file_name=f"{article_slug}.csv",
                mime="text/csv",
                key=f"csv_btn_{idx}"
            )
            
            single_pdf = generate_pdf_report(selected_source, [entry])
            d_col2.download_button(
                label="📄 Export Article PDF",
                data=single_pdf,
                file_name=f"{article_slug}.pdf",
                mime="application/pdf",
                key=f"pdf_btn_{idx}"
            )
            
            st.divider()

    # --- MASTER UNLIMITED DOWNLOAD AT THE BOTTOM ---
    st.subheader(f"📥 Export Complete Feed Report ({len(filtered_entries)} Articles)")
    all_col1, all_col2 = st.columns(2)
    
    full_export_data = []
    for e in filtered_entries:
        full_export_data.append({
            "Title": e.title,
            "Published Date": getattr(e, 'published', getattr(e, 'updated', 'N/A')),
            "Link": e.link,
            "Summary": clean_html(getattr(e, 'summary', ''))
        })
    
    full_csv = pd.DataFrame(full_export_data).to_csv(index=False).encode('utf-8')
    full_pdf = generate_pdf_report(selected_source, filtered_entries)
    
    source_slug = clean_filename(selected_source)
    
    all_col1.download_button(
        label=f"📊 Download All ({len(filtered_entries)}) Articles CSV",
        data=full_csv,
        file_name=f"Full_Feed_{source_slug}_{datetime.now().strftime('%Y%m%d')}.csv",
        mime="text/csv",
        key="full_csv_btn"
    )
    
    all_col2.download_button(
        label=f"📄 Download All ({len(filtered_entries)}) Articles PDF",
        data=full_pdf,
        file_name=f"Full_Feed_{source_slug}_{datetime.now().strftime('%Y%m%d')}.pdf",
        mime="application/pdf",
        key="full_pdf_btn"
    )

else:
    st.warning("Currently unable to retrieve live articles for this feed. Try selecting another source from the sidebar.")
