import streamlit as st
import feedparser
import urllib.request
import re
import pandas as pd
from datetime import datetime
from fpdf import FPDF

# Page configuration
st.set_page_config(
    page_title="Agri Pulse AI - Global Agricultural Dashboard",
    page_icon="🌾",
    layout="wide"
)

# Custom Styling (CSS)
st.markdown("""
<style>
    .main-title {
        font-size: 2.3rem;
        font-weight: 700;
        color: #2E7D32;
        margin-bottom: 0px;
    }
    .sub-title {
        color: #555555;
        font-size: 1rem;
        margin-bottom: 25px;
    }
    .news-card {
        background-color: #f9fbf9;
        padding: 18px;
        border-radius: 10px;
        border-left: 5px solid #2E7D32;
        margin-bottom: 15px;
        box-shadow: 0 1px 3px rgba(0,0,0,0.1);
    }
</style>
""", unsafe_allow_html=True)

# App Title Header
st.markdown('<div class="main-title">🌾 Agri Pulse AI Dashboard</div>', unsafe_allow_html=True)
st.markdown('<div class="sub-title">Real-time global agricultural market intelligence and automated AI summaries.</div>', unsafe_allow_html=True)

# Free & Reliable Feeds
rss_feeds = {
    "ScienceDaily - Ag & Food Research": "https://www.sciencedaily.com/rss/plants_animals/agriculture_and_food.xml",
    "Farms.com - Global Industry News": "https://m.farms.com/farmspages/generate_rss_portal/tabid/2854/default.aspx",
    "BBC - Climate & Environment": "https://feeds.bbci.co.uk/news/science_and_environment/rss.xml"
}

# Helper Functions
def fetch_feed(url):
    try:
        req = urllib.request.Request(
            url, 
            headers={'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/120.0.0.0 Safari/537.36'}
        )
        xml_data = urllib.request.urlopen(req, timeout=10).read()
        return feedparser.parse(xml_data)
    except Exception as e:
        st.error(f"Error connecting to server: {e}")
        return None

def clean_html(raw_html):
    return re.sub(re.compile('<.*?>'), '', raw_html)

def call_ai_summary(text, api_key):
    try:
        from openai import OpenAI
        client = OpenAI(base_url="https://api.groq.com/openai/v1", api_key=api_key)
        response = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[
                {"role": "system", "content": "You are an expert agronomy consultant. Provide a 2-bullet point summary highlighting key agricultural implications."},
                {"role": "user", "content": text}
            ],
            max_tokens=150
        )
        return response.choices[0].message.content
    except Exception as err:
        return f"AI Service Error: {err}"

# Pure Python FPDF Report Generator
class AgriPDFReport(FPDF):
    def header(self):
        self.set_fill_color(27, 94, 32) # Dark Green Banner
        self.rect(0, 0, 210, 25, 'F')
        self.set_font('Arial', 'B', 14)
        self.set_text_color(255, 255, 255)
        self.cell(0, 8, 'Agri Pulse AI -- News Intelligence Report', 0, 1, 'L')
        self.set_font('Arial', '', 9)
        self.cell(0, 4, 'Automated Agricultural Market & Research Briefing', 0, 1, 'L')
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by Agri Pulse AI Dashboard', 0, 0, 'C')

def generate_pdf_report(source_name, entries):
    pdf = AgriPDFReport()
    pdf.add_page()
    
    # Metadata Block
    pdf.set_font('Arial', 'B', 10)
    pdf.set_text_color(46, 125, 50)
    pdf.cell(35, 6, "Source Feed:", 0, 0)
    pdf.set_font('Arial', '', 10)
    pdf.set_text_color(50, 50, 50)
    pdf.cell(60, 6, source_name, 0, 0)
    
    pdf.set_font('Arial', 'B', 10)
    pdf.set_text_color(46, 125, 50)
    pdf.cell(35, 6, "Date Generated:", 0, 0)
    pdf.set_font('Arial', '', 10)
    pdf.set_text_color(50, 50, 50)
    pdf.cell(0, 6, datetime.now().strftime("%B %d, %Y"), 0, 1)
    
    pdf.ln(5)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(5)
    
    # Section Header
    pdf.set_font('Arial', 'B', 12)
    pdf.set_text_color(27, 94, 32)
    pdf.cell(0, 8, "Aggregated News & Research Summaries", 0, 1)
    pdf.ln(2)

    # Article Listings
    for idx, item in enumerate(entries[:10], 1):
        pdf.set_font('Arial', 'B', 10)
        pdf.set_text_color(27, 94, 32)
        
        # Clean special non-latin characters for standard PDF safety
        safe_title = item.title.encode('latin-1', 'replace').decode('latin-1')
        pdf.multi_cell(0, 5, f"{idx}. {safe_title}")
        
        pub_date = getattr(item, 'published', getattr(item, 'updated', 'Recent'))
        pdf.set_font('Arial', 'I', 8)
        pdf.set_text_color(128, 128, 128)
        pdf.cell(0, 4, f"Published: {pub_date}", 0, 1)
        
        summary_text = clean_html(getattr(item, 'summary', 'No summary available.'))[:300]
        safe_summary = summary_text.encode('latin-1', 'replace').decode('latin-1')
        
        pdf.set_font('Arial', '', 9)
        pdf.set_text_color(60, 60, 60)
        pdf.multi_cell(0, 4.5, f"{safe_summary}...")
        pdf.ln(4)

    return bytes(pdf.output())

# Sidebar Controls
with st.sidebar:
    st.header("⚙️ Dashboard Controls")
    selected_source = st.selectbox("📰 Select News Source", list(rss_feeds.keys()))
    
    st.divider()
    st.header("🤖 AI Integration Settings")
    ai_key = st.text_input("Enter Groq / OpenAI API Key", type="password", help="Get a free key from console.groq.com")
    ai_enabled = st.checkbox("Enable AI Article Summaries", value=False)

# Fetch Data
feed_url = rss_feeds[selected_source]
feed_data = fetch_feed(feed_url)

if feed_data and feed_data.entries:
    # Metrics Header
    col1, col2, col3 = st.columns(3)
    col1.metric("Active Source", selected_source.split(" - ")[0])
    col2.metric("Total Articles Loaded", len(feed_data.entries))
    col3.metric("System Status", "Live Connection 🟢")

    st.divider()

    # Search Bar
    search_term = st.text_input("🔍 Search Articles by Keyword / Crop Name", "").lower()

    filtered_entries = [
        entry for entry in feed_data.entries 
        if search_term in entry.title.lower() or search_term in getattr(entry, 'summary', '').lower()
    ]

    # Sidebar Export Tools
    with st.sidebar:
        st.divider()
        st.header("📥 Export Intelligence Report")
        
        # CSV Export
        export_data = []
        for e in filtered_entries[:15]:
            export_data.append({
                "Title": e.title,
                "Published Date": getattr(e, 'published', getattr(e, 'updated', 'N/A')),
                "Link": e.link,
                "Summary": clean_html(getattr(e, 'summary', ''))
            })
        df_export = pd.DataFrame(export_data)
        csv_bytes = df_export.to_csv(index=False).encode('utf-8')
        
        st.download_button(
            label="📊 Download CSV Data",
            data=csv_bytes,
            file_name=f"Agri_News_{datetime.now().strftime('%Y%m%d')}.csv",
            mime="text/csv",
            use_container_width=True
        )

        # PDF Export
        try:
            pdf_bytes = generate_pdf_report(selected_source, filtered_entries)
            st.download_button(
                label="📄 Download PDF Report",
                data=pdf_bytes,
                file_name=f"Agri_Intelligence_Report_{datetime.now().strftime('%Y%m%d')}.pdf",
                mime="application/pdf",
                use_container_width=True
            )
        except Exception as e:
            st.caption(f"PDF Notice: {e}")

    st.subheader(f"Showing Top Articles ({len(filtered_entries)})")

    # Render Cards
    for entry in filtered_entries[:10]:
        clean_summary = clean_html(getattr(entry, 'summary', 'No summary available.'))
        pub_date = getattr(entry, 'published', getattr(entry, 'updated', 'Recent'))
        
        with st.container():
            st.markdown(f"### [{entry.title}]({entry.link})")
            st.caption(f"📅 Published: {pub_date}")
            st.write(clean_summary[:300] + ("..." if len(clean_summary) > 300 else ""))
            
            if ai_enabled:
                if ai_key:
                    with st.expander("✨ View AI Insights & Agronomy Summary"):
                        with st.spinner("Analyzing article..."):
                            summary_result = call_ai_summary(clean_summary, ai_key)
                            st.write(summary_result)
                else:
                    st.warning("Please enter your API key in the sidebar menu to unlock AI Summaries.")
            
            st.divider()
else:
    st.warning("Currently unable to retrieve live articles for this feed. Try selecting another source from the sidebar.")
